name: Test partitioned builds

on:
  push:
    branches:
    - main
  pull_request:

env:
  # bump to purge caches
  ACTIONS_CACHE_VERSION: v1
  CLOJURE_CLI_VERSION: 1.12.0.1479
  CLOJURE_CACHE_PATHS: |
    ~/.m2/repository
    ~/.gitlibs
    ~/.deps.clj

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if we need to cache Clojure dependencies
        id: cache-check
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CLOJURE_CACHE_PATHS }}
          key: cljdeps-${{ env.ACTIONS_CACHE_VERSION }}-${{ hashFiles('deps.edn') }}
          lookup-only: true
      - name: Prepare java
        if: steps.cache-check.outputs.cache-hit != 'true'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install clojure tools
        if: steps.cache-check.outputs.cache-hit != 'true'
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: ${{ env.CLOJURE_CLI_VERSION }}
      - name: Download Clojure deps
        if: steps.cache-check.outputs.cache-hit != 'true'
        working-directory: 
        run: ./bin/kaocha --version
      - name: Save Clojure dependencies
        if: steps.cache-check.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CLOJURE_CACHE_PATHS }}
          key: ${{ steps.cache-check.outputs.cache-primary-key }}
      - name: Profiling Cache
        id: profiling
        uses: actions/cache/restore@v4
        with:
          path: kaocha-profiling.edn
          key: force-cache-miss-profiling-${{ env.ACTIONS_CACHE_VERSION }}-${{ github.ref }}-${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            profiling-${{ env.ACTIONS_CACHE_VERSION }}-${{ github.ref }}-${{ github.sha }}-
            profiling-${{ env.ACTIONS_CACHE_VERSION }}-${{ github.ref }}-
            profiling-${{ env.ACTIONS_CACHE_VERSION }}-
      - name: Ensure profiling file exists
        run: |
          if [ ! -f kaocha-profiling.edn ]; then
            touch kaocha-profiling.edn
          fi
          set -x
          cat kaocha-profiling.edn
      - name: Share profiling results with tests
        uses: actions/upload-artifact@v4
        with:
          name: kaocha-profiling
          path: kaocha-profiling.edn
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: setup
    strategy:
      matrix:
        id: [0,1,2,3,4,5,6,7,8,9]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: ${{ env.CLOJURE_CACHE_PATHS }}
          key: cljdeps-${{ env.ACTIONS_CACHE_VERSION }}-${{ hashFiles('deps.edn') }}
          fail-on-cache-miss: true
      - name: Download profiling results
        uses: actions/download-artifact@v4
        with:
          name: kaocha-profiling
      - name: Ensure profiling file exists
        run: cat kaocha-profiling.edn
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: ${{ env.CLOJURE_CLI_VERSION }}
      - name: Restore Clojure cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CLOJURE_CACHE_PATHS }}
          key: cljdeps-${{ env.ACTIONS_CACHE_VERSION }}-${{ hashFiles('deps.edn') }}
          fail-on-cache-miss: true
      - name: Run tests
        run: ./bin/kaocha --read-profiling-file kaocha-profiling.edn --write-profiling-file current-kaocha-profiling-${{ strategy.job-index }}.edn --partition-index ${{ strategy.job-index }} --partitions ${{ strategy.job-total }} --partition-strategy :test-time
      - name: Upload profiling results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: current-kaocha-profiling
          path: current-kaocha-profiling-${{ strategy.job-index }}.edn
  result:
    timeout-minutes: 5
    # TODO fail if test fails
    if: always()
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download test timings
        uses: actions/download-artifact@v4
        with:
          pattern: current-kaocha-profiling-*.edn
          merge-multiple: true
      - name: Combine results
        run: |
          rm -f kaocha-profiling.edn
          ls current-kaocha-profiling-*.edn
          for i in current-kaocha-profiling-*.edn; do cat $i >> kaocha-profiling.edn; done
          cat kaocha-profiling.edn
      - name: Update Profiling Cache
        id: profiling
        uses: actions/cache/save@v4
        with:
          path: kaocha-profiling.edn
          key: profiling-${{ env.ACTIONS_CACHE_VERSION }}-${{ github.ref }}-${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
